// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © ripster47

//@version=5
indicator('Ripster EMA Clouds V5', 'Ripster EMA Clouds', overlay=true, explicit_plot_zorder=true)

f_ma(_src,_malen, _matype) =>
    float result = 0
    if _matype == 'EMA'
        result := ta.ema(_src, _malen)
        result
    if _matype == 'SMA'
        result := ta.sma(_src, _malen)
        result
    if _matype == 'HMA'
        result := ta.hma(_src, _malen)
        result
    if _matype == 'WMA'
        result := ta.wma(_src, _malen)
        result
    result

//res = input(title="Resolution", type=resolution, defval="240")

//plot(out1, color=green, offset=ma_offset)
//plot(out2, color=red, offset=ma_offset)

//lengthshort = input(8, minval = 1, title = "Short EMA Length")
//lengthlong = input(200, minval = 2, title = "Long EMA Length")
//emacloudleading = input(50, minval = 0, title = "Leading Period For EMA Cloud")
//src = input(hl2, title = "Source")

src             = input.source(title='Source', defval=hl2)
matype          = input.string(title='MA Type', defval='EMA', options=['EMA', 'SMA', 'HMA', 'WMA'])
ma_offset       = input.int(title='MA Offset', defval=0)
showLine        = input.bool(false, title='Display EMA Line')
emacloudleading = input.int( 0, minval=0, title='Plot Offset')

ema1            = input.bool( true, title='Show EMA Cloud-1')
ema2            = input.bool( true, title='Show EMA Cloud-2')
ema3            = input.bool( true, title='Show EMA Cloud-3')
ema4            = input.bool( true, title='Show EMA Cloud-4')
ema5            = input.bool( true, title='Show EMA Cloud-5')

ma_len1         = input(title='EMA1 Short Length', defval=8)
ma_len2         = input(title='EMA1 Long Length' , defval=9)
ma_len3         = input(title='EMA2 Short Length', defval=5)
ma_len4         = input(title='EMA2 Long Length' , defval=13)
ma_len5         = input(title='EMA3 Short Length', defval=34)
ma_len6         = input(title='EMA3 Long Length' , defval=50)
ma_len7         = input(title='EMA4 Short Length', defval=72)
ma_len8         = input(title='EMA4 Long Length' , defval=89)
ma_len9         = input(title='EMA5 Short Length', defval=180)
ma_len10        = input(title='EMA5 Long Length' , defval=200)

showlong        = input.bool(false, title='Show Long Alerts')
showshort       = input.bool(false, title='Show Short Alerts')

mashort1        = f_ma(src, ma_len1, matype)
malong1         = f_ma(src, ma_len2, matype)
mashort2        = f_ma(src, ma_len3, matype)
malong2         = f_ma(src, ma_len4, matype)
mashort3        = f_ma(src, ma_len5, matype)
malong3         = f_ma(src, ma_len6, matype)
mashort4        = f_ma(src, ma_len7, matype)
malong4         = f_ma(src, ma_len8, matype)
mashort5        = f_ma(src, ma_len9, matype)
malong5         = f_ma(src, ma_len10, matype)

cloudcolour1    = mashort1 >= malong1 ? #036103 : #880e4f // dark-green : dark-magenta
cloudcolour2    = mashort2 >= malong2 ? #4caf50 : #f44336 //  mid-green : orangered
cloudcolour3    = mashort3 >= malong3 ? #2196f3 : #ffb74d //   sky-blue : orange
cloudcolour4    = mashort4 >= malong4 ? #009688 : #f06292 //  turquoise : pink
cloudcolour5    = mashort5 >= malong5 ? #05bed5 : #e65100 //       cyan : orangered
//03abc1

mashortcolor1   = mashort1 >= mashort1[1] ? color.olive : color.maroon
mashortcolor2   = mashort2 >= mashort2[1] ? color.olive : color.maroon
mashortcolor3   = mashort3 >= mashort3[1] ? color.olive : color.maroon
mashortcolor4   = mashort4 >= mashort4[1] ? color.olive : color.maroon
mashortcolor5   = mashort5 >= mashort5[1] ? color.olive : color.maroon

malongcolor1    = malong1 >= malong1[1] ? color.green : color.red
malongcolor2    = malong2 >= malong2[1] ? color.green : color.red
malongcolor3    = malong3 >= malong3[1] ? color.green : color.red
malongcolor4    = malong4 >= malong4[1] ? color.green : color.red
malongcolor5    = malong5 >= malong5[1] ? color.green : color.red

mashortline1    = plot(ema1 ? mashort1 : na, color=mashortcolor1, linewidth=1, offset=emacloudleading, title='Short Leading EMA1', display=showLine ? display.pane : display.none)
mashortline2    = plot(ema2 ? mashort2 : na, color=mashortcolor2, linewidth=1, offset=emacloudleading, title='Short Leading EMA2', display=showLine ? display.pane : display.none)
mashortline3    = plot(ema3 ? mashort3 : na, color=mashortcolor3, linewidth=1, offset=emacloudleading, title='Short Leading EMA3', display=showLine ? display.pane : display.none)
mashortline4    = plot(ema4 ? mashort4 : na, color=mashortcolor4, linewidth=1, offset=emacloudleading, title='Short Leading EMA4', display=showLine ? display.pane : display.none)
mashortline5    = plot(ema5 ? mashort5 : na, color=mashortcolor5, linewidth=1, offset=emacloudleading, title='Short Leading EMA5', display=showLine ? display.pane : display.none)

malongline1     = plot(ema1 ? malong1  : na, color=malongcolor1,  linewidth=1, offset=emacloudleading, title='Long Leading EMA1',  display=showLine ? display.pane : display.none)
malongline2     = plot(ema2 ? malong2  : na, color=malongcolor2,  linewidth=1, offset=emacloudleading, title='Long Leading EMA2',  display=showLine ? display.pane : display.none)
malongline3     = plot(ema3 ? malong3  : na, color=malongcolor3,  linewidth=1, offset=emacloudleading, title='Long Leading EMA3',  display=showLine ? display.pane : display.none)
malongline4     = plot(ema4 ? malong4  : na, color=malongcolor4,  linewidth=1, offset=emacloudleading, title='Long Leading EMA4',  display=showLine ? display.pane : display.none)
malongline5     = plot(ema5 ? malong5  : na, color=malongcolor5,  linewidth=1, offset=emacloudleading, title='Long Leading EMA5',  display=showLine ? display.pane : display.none)

fill(mashortline1, malongline1, color=color.new(cloudcolour1, 45), title='MA Cloud1')
fill(mashortline2, malongline2, color=color.new(cloudcolour2, 65), title='MA Cloud2')
fill(mashortline3, malongline3, color=color.new(cloudcolour3, 70), title='MA Cloud3')
fill(mashortline4, malongline4, color=color.new(cloudcolour4, 65), title='MA Cloud4')
fill(mashortline5, malongline5, color=color.new(cloudcolour5, 65), title='MA Cloud5')

